### ISSUE TITLE
Vserial_hi parameter missing

### ISSUE THREAD

**Issue by belaa** [craiglagegit/Poisson_CCD22#1]
The `bf.cfg` files in /data set the voltage parameters according to:

```
Vbb = -60.0         # Back bias
Vparallel_lo = -8.0     # Parallel Low Voltage
Vparallel_hi = 4.0      # Parallel High Voltage
Vserial_lo = -4.0       # Serial Low Voltage
Vserial_lo = 6.0        # Serial High Voltage 
```

`Vserial_lo` corresponds to both serial low/high voltage. However in `multigrid.cpp` it seems that `Vserial_hi` is never actually called:

```
Vbb = GetDoubleParam(inname, "Vbb", -50.0);             // Back bias
  Vparallel_lo = GetDoubleParam(inname, "Vparallel_lo", -8.0);  // Parallel Low Voltage
  Vparallel_hi = GetDoubleParam(inname, "Vparallel_hi", 4.0);   // Parallel High Voltage
  Vserial_lo = GetDoubleParam(inname, "Vserial_lo", -6.0);  // Serial Low Voltage
  Vaverage = (8.0 * Vparallel_lo + 4.0 * Vparallel_hi) / 12.0;
```

**Comment by dkirkby** [comment]
I just checked that all the .cfg files under data/ have this issue.  Even though Vserial_hi is never used by the code, it looks like the value of Vserial_lo is being overwritten with the wrong value (6V instead of -4V).

Another minor issue I noticed in the .cfg files is that most of the concentrations are specified with units of `cm^-2` in their comments (all except `BackgroundDoping`).  Shouldn't that be `cm^-3` throughout?

**Comment by craiglagegit** [comment]
Dave,

Thanks for pointing these things out, and sorry it has taken me so long to reply.  I made the following changes:

(1) I removed the -lsz from the Makefile as you suggested.

(2) I corrected the Vserial_lo in the .cfg file to read Vserial_hi

The cm^-2 and cm^-3 differences are correct as they are.  The BackgroundDoping is a volume charge density throughout the silicon and has units of cm^-3.  The ChannelDoping and ChannelStopDoping are implants introduced from the frontside of the silicon, and so they have units of cm^-2.  The volume charge density in the channel and channel stop regions in units of cm^-3 are then a function of the depth of the implants, controlled by the ChannelDepth and ChannelStopDepth parameters.  So, for example, if I have ChannelDoping=1.0E12, and a square profile (ChannelProfile=0) with a ChannelDepth = 1.0 microns, the volume charge density in that region will be 1.0E12 cm^-2 / 1.0E-4 cm = 1.0E16 cm^-3.  The program should (hopefully) calculate all of this correctly.  This is common usage in semiconductors.

These volume charge densities in cm^-3 are plotted in the "*_1D_Potentials.pdf" plots, although the units are somewhat cryptic.

Please let me know if you have more questions or concerns.

Thanks,

Craig

**Comment by dkirkby** [comment]
Thanks for the clarification and updates.  I was thrown off by how similar the values were, all around 1e12, and so assumed the units must the same.

**Comment by craiglagegit** [comment]
I understand.  It's kind of a coincidence that the values are so similar.

**Comment by craiglagegit** [comment]
I'm closing this issue.  I anyone disagrees, please holler.
