### ISSUE TITLE
Remove dependency on unused sz library

### ISSUE THREAD

**Issue by dkirkby** [craiglagegit/Poisson_CCD22#2]
The sz library is an optional component of HDF5 and not required to build Poisson.  This issue is a suggestion to remove `-lsz` from the Makefile link command.  I have tested that this works on OS-X and CentOS.

**Comment by craiglagegit** [comment]
Good suggestion.  The -lsz has been removed.

Thanks,
Craig

**Comment by craiglagegit** [comment]
I'm closing this issue.  If anyone disagrees, please holler.
